[tool.poetry]
name = "amla-streamlit"
version = "0.1.0"
description = "Streamlit app for AT3"
authors = ["Martin Neloe <Martin.A.Neloe@student.edu.au>"]
readme = "README.md"
packages = [{include = "amla_streamlit"}]

[tool.poetry.dependencies]
python = "^3.10"
streamlit = "1.27.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
